### ISSUE TITLE
Extremely large logs because of $logger->debug in RsyncSource

### ISSUE THREAD

**Issue by kachkaev** [kbond/ZenstruckBackupBundle#10]
Symfony production environment usually has a `fingers_corssed` logger, which dumps all log messages to a file only if there is an error.

During a backup, an error may occur when syncing to a remote server, e.g. if the connection is weak.  Because of [`RsyncSource`](https://github.com/kbond/ZenstruckBackupBundle/blob/v0.5.0/src/Source/RsyncSource.php), the logs may become terribly long.

Here is the cause:

``` php
$process->run(
            function ($type, $buffer) use ($logger) {
                $logger->debug($buffer);
            }
        );
```

In my project, I rsync a directory with about 10,000 small files and then send the archive to a remote folder. The cron job runs every 5 minutes. If the upload fails, the `fingers_crossed` logger calls the `nested` one and appends thousands of lines to a file in `app/log`. Thus, some of the recent daily logs grew up to 800 MB! :–)

I know that you can disable debug messages in the nested logger like this, but I'm not sure this a good solution:

``` yml
# app/config_prod.yml
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  rotating_file
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: warning # <------ instead of debug
            max_files: 10
        console:
            type:  console
```

Seeing debug messages for failed app request is really handy, so disabling them globally is undesired.

What problem does the detailed logging of `rsync` solve? In which cases may it be helpful?
