### ISSUE TITLE
Multiple destinations in one profile

### ISSUE THREAD

**Issue by kachkaev** [kbond/ZenstruckBackupBundle#4]
It seems logical to let people dump a backup to multiple destinations at once. The config would change the following way:

``` yml
zenstruck_backup:
    #...
    profiles:
        daily:
            scratch_dir: "%kernel.root_dir%/cache/backup"
            sources: [database, files]
            namer: daily
            processor: zip
            destinations:
                - some_local_dir
                - my_amazon_bucket_1
                - my_amazon_bucket_2
```

AFAIK it is possible to keep "destination" as an optional filed in the config to maintain backward compatibility.
