### ISSUE TITLE
Timezone support in namers

### ISSUE THREAD

**Issue by kachkaev** [kbond/ZenstruckBackupBundle#5]
The timestamps in the names of the shapshots use the time zone of the server. It can be handy, however, to use some other one, e.g UTC:

``` yaml
#...
    namers:
        snapshot:
            timestamp:
                format: Y-m-d-Hi
                prefix: my-backup-
                timezone_identifier: UTC
                # or:
                timezone_offset: +0000

```
